### ISSUE TITLE
Asserting Queue on queueable actions

### ISSUE THREAD

**Issue by ronssij** [spatie/laravel-queueable-action#24]
I am having issues asserting queued actions on unit-testing. But when running on post it is working fine.

![image](https://user-images.githubusercontent.com/24932380/75138987-829e2f00-5726-11ea-933c-07209887e4cb.png)

![image](https://user-images.githubusercontent.com/24932380/75137876-bf1c5b80-5723-11ea-8cba-b7f42f30bc9d.png)

![image](https://user-images.githubusercontent.com/24932380/75137946-ed01a000-5723-11ea-8361-a82f6c2a1d44.png)

![image](https://user-images.githubusercontent.com/24932380/75138249-b0827400-5724-11ea-8919-6c307c0fca9d.png)

**Comment by nathanheffley** [comment]
What if you modified your test to check that an `ActionJob` (from this package) was dispatched?

If you view the source code, you will see that when you call `execute` it actually dispatches an `ActionJob`. https://github.com/spatie/laravel-queueable-action/blob/7afdb9733b51022240c4d6639de7aea890bb95c5/src/QueueableAction.php#L25

This is because the actions you create are not actually jobs. They are just run inside of an `ActionJob` that disguises itself in your workers as if it was the action being run.
