### ISSUE TITLE
Execute method is hardcoded without abstract/interface

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-queueable-action#9]
The method to be executed is hardcoded but there is no `Action` abstract class or interface which forces the user to define a `execute()` method.
For me it would be even better if the method name isn't enforced because laravel standard is `handle()` and `__invoke()` could also be great. So how about using `__call()` and pass the called method name to the queue job?
This way the user could name the executing method how ever he wants.

**Comment by brendt** [comment]
`__invoke` is the obvious answer here. Unfortunately there are some caveats if you're composing actions of actions: using `$this` in combination with an invokable instance property is a little clumsy. Take a look at the following:

```php
class ParentAction
{
    public function __construct(SubAction $subAction) { /* … */ }

    public function __invoke()
    {
        $subResult = ($this->subAction)();
    }
}
```

You can't call `$this->subAction()` directly, because PHP will only look for a method on the parent action. Furthermore, PhpStorm cannot analyse the `($this->subAction)()` syntax. This means that if subaction would need parameters, PhpStorm wouldn't be able to tell you.

Because of these caveats you end up writing `$this->subAction->__invoke()`, which we don't want.

Moving on to `handle`. There's a good reason not to use it, specifically because Laravel's behaviour. `handle` allows for method dependency injection. The goal of this package and this "action pattern" is to specifically counteract that behaviour. We want to use the constructor for general DI, and the method arguments to pass context-specific data. This is the exact opposite of how Laravel's `handle` works in all cases I'm aware of: jobs and commands. 

This leaves us having to pick another name to, one) have proper tooling support, and two) avoid confusion with Laravel. 

We also cannot provide an interface with an `execute` method, because each action is allowed to specify its own specific parameter list in `execute`. 

I'm afraid that we're reaching the limits of PHP's capabilities at this point (method overloading might offer some answers here). We need to rely on some kind of magic to make this package useful and flexible, and sacrifice correctness instead.

**Comment by brendt** [comment]
The only thing we could do to improve DX is to add a check whether the "execute" method is available on the action before executing it, and throw a human friendly exception if not (https://github.com/spatie/laravel-queueable-action/blob/master/src/ActionJob.php#L43)

**Comment by Gummibeer** [comment]
@brendt thanks for the explanation. I don't use Sub-Actions atm, that's why `__invoke()` come to my mind as a good/easy way to execute actions like they were actions/functions/methods and not like they were normal classes which could have multiple public methods.
Also as some kind of [junior prevention](https://www.youtube.com/watch?v=HZD1XYiPyfg) doing things which shouldn't be done.
I beliefe that adding the check isn't necessary - the default PHP exception is very self explanatory and it will just slow correct created actions down.
